### ISSUE TITLE
msq sql server. Совместимость с oscript 15

### ISSUE THREAD

**Issue by ret-Phoenix** [ret-Phoenix/oscript-sql#13]
ЗапросВставка.ВыполнитьКоманду();

Внешнее исключение (System.MissingMethodException): Метод не найден: "System.Collections.Generic.IEnumerator`1<ScriptEngine.Machine.IValue> ScriptEngine.HostedScript.Library.StructureImpl.GetEnumerator()".}  
    ЗапросВставка.ВыполнитьКоманду();

**Comment by dmpas** [comment]
так нет же ещё 15-й в нугете. а так, там вместо IEnumerable<IValue> будет IENumerable<KeyAndValueImpl>.

см https://github.com/EvilBeaver/OneScript/issues/310

**Comment by ret-Phoenix** [comment]
Спасибо, я это видел, пока руки не дошли до подгонки для 15 релиза
