### ISSUE TITLE
Время ожидания при выполнении запроса

### ISSUE THREAD

**Issue by Stepa86** [ret-Phoenix/oscript-sql#18]
Пытаюсь сделать бекап с использованием оскрипта и этой библиотеки. На маленьких базах все ок, на больших появилось исключение "Истекло время ожидания (Timeout)". Им можно как-то управлять? Не нашел никакого упоминания таймаута.

`{Модуль g:\GIT_Repo\ci\src\ExecQuery.os / Ошибка в строке: 64 / Внешнее исключение (System.Data.SqlClient.SqlException): Истекло время ожидания (Timeout). Время ожидания истекло до завершения
 операции или сервер не отвечает.
The backup or restore was aborted.
10 percent processed.
20 percent processed.
30 percent processed.
40 percent processed.
50 percent processed.
60 percent processed.
70 percent processed.}`

В скрипте выглядит так
`Соединение = Новый Соединение();
Соединение.ТипСУБД = Соединение.ТипыСУБД.MSSQLServer;
Соединение.Сервер = Параметры["Сервер"];	
Соединение.ИмяПользователя = Параметры["Пользователь"];
Соединение.Пароль = Параметры["Пароль"];
Соединение.ИмяБазы = Параметры["ИмяБазы"];

Сообщить("Открываю соединение");
Соединение.Открыть();

Запрос = Новый Запрос();
Запрос.УстановитьСоединение(Соединение);
Запрос.Текст = ТекстЗапроса;
Сообщить("Начинаю выполнять запрос");
Запрос.ВыполнитьКоманду();
Сообщить("Выполнил запрос");

Сообщить("Ну и хватит на сегодня. Закрываю соединение");
Соединение.Закрыть();`

ЗЫ Может бекапить скульные базы в оскрипте нужно как то иначе и я фигней страдаю?

**Comment by ret-Phoenix** [comment]
Чем не устраивает бекапирование средствами SQL?
Насчет таймаута - надо посмотреть.

**Comment by Stepa86** [comment]
Я хочу заскриптовать выгрузку боевой базы в базу разработки с переподключением к хранилищу. Что-то делать скулем, а что-то скриптом не очень хочу. Таймаут правильная вещь, просто я бы хотел его уметь устанавливать.

**Comment by ret-Phoenix** [comment]
Понял, тогда да, лучше через OneScript, постараюсь сегодня/завтра глянуть по тайму.
Если подключено в MS SQL sqlcmd - пока его юзай. понимаю, что не безопасно, но некоторые ПО требуют его включения.

**Comment by rsyuzyov** [comment]
@Stepa86, а можно попросить потом выложить на гитхабе или на гисте? Вещь-то хорошая.

**Comment by Stepa86** [comment]
@rsyuzyov , не торопите меня. Я тут ваще новенький и это мой первый скрипт. Мне страшно...

А куда правильнее выкладывать? Сюда в примеры запулреквестить, создать свой репо или куда то еще?

**Comment by ret-Phoenix** [comment]
Создать свой репо и залить туда, думаю будет интересная вещь.

**Comment by EvilBeaver** [comment]
@Stepa86 главное, не забыть потом сюда написать адрес своего репо, а то как мы его найдем?

**Comment by Stepa86** [comment]
@EvilBeaver это сарказм? Или через профиль не все находится?

Начал вести репо тут https://github.com/Stepa86/oScript-Examples

**Comment by EvilBeaver** [comment]
@Stepa86 ни в коем случае не сарказм. В профиле может быть много всего. Однозначно установить, что данная беседа относится к конкретному репо - не всегда возможно. А так - есть ссылка, все понятно.
