### ISSUE TITLE
Проблема с результатом выборки MS SQL

### ISSUE THREAD

**Issue by AlexStrizh** [ret-Phoenix/oscript-sql#30]
Если сделать выборку по активным jobs агента сервера MS SQL (EXEC хранимая процедура), то в возвращаемой ТЗ возвращаются не все колонки выборки, а в колонках значения из других колонок.

**Comment by ret-Phoenix** [comment]
Приведите код.

**Comment by AlexStrizh** [comment]
[https://raw.githubusercontent.com/AlexStrizh/utils-deploying-db-1c/master/src/ssajm.os](https://raw.githubusercontent.com/AlexStrizh/utils-deploying-db-1c/master/src/ssajm.os)

Правда я уже переделал под TMSSQL, но если выполнить хранимую процедуру посредством библиотеки `sql`, то проблема должна повториться. Проблема была на MS SQL 2012.

Результат = УправлениеMSSQL.ВыполнитьЗапрос("`EXEC msdb.dbo.sp_help_job;`", "msdb", Истина);

**Comment by ret-Phoenix** [comment]
Проверил, у меня отработало нормально, разве что job_id пустой вернуло, из-за не реализованного типа данных.

`#Использовать sql
#Использовать gui

УправляемыйИнтерфейс = Новый УправляемыйИнтерфейс();
Форма = УправляемыйИнтерфейс.СоздатьФорму();


КоннекстМССКЛ = Новый Соединение();
КоннекстМССКЛ.ТипСУБД = КоннекстМССКЛ.ТипыСУБД.MSSQLServer;
КоннекстМССКЛ.Сервер = "<АдресСервера>";
КоннекстМССКЛ.ИмяБазы = "master";
КоннекстМССКЛ.Открыть();

Запрос = Новый Запрос();
Запрос.УстановитьСоединение(КоннекстМССКЛ);
Запрос.Текст = "EXEC msdb.dbo.sp_help_job";

ТЗ = Запрос.Выполнить().Выгрузить();

ПровайдерТЗ = Новый Провайдер;
ПровайдерТЗ.Источник = ТЗ;

Поле1 = Форма.Элементы.Добавить("ТаблицаФормы1", "ТаблицаФормы", Неопределено);
Поле1.ПутьКДанным = ПровайдерТЗ;
Поле1.Заголовок = "Провайдер - ТЗ";
Поле1.ПоложениеЗаголовка = УправляемыйИнтерфейс.ПоложениеЗаголовка.Верх;
Поле1.Закрепление = УправляемыйИнтерфейс.СтильЗакрепления.Заполнение;

Форма.Показать();`

**Comment by AlexStrizh** [comment]
Проверил еще раз, см. колонка enabled
![image](https://user-images.githubusercontent.com/25724999/43066685-fd744d8c-8e6d-11e8-9c8c-528572a0c399.png)
вот тот же результат другими средствами
![image](https://user-images.githubusercontent.com/25724999/43066842-70f72e0a-8e6e-11e8-85f8-863ae71bd124.png)

**Comment by ret-Phoenix** [comment]
Обновил плагин: https://github.com/ret-Phoenix/oscript-sql/releases/tag/1.0.6778.26879
