### ISSUE TITLE
Доработать тесты MS SQL для возможности пропуска тестов при запуске в другой инфраструктуре

### ISSUE THREAD

**Issue by artbear** [ret-Phoenix/oscript-sql#9]
В текущих тестах MS SQL есть привязка к конкретному инстансу и базе MS SQL.
У контрибьюторов доступа к инфраструктуре нет, поэтому тесты у нас будут падать.

Предлагаю пропускать тесты, если нет доступа к инстансу.
Важно - именно пропускать как нереализованные, а не показывать их вообще или отмечать как упавшие.

**Comment by ret-Phoenix** [comment]
Теперь ищет файл с параметрами соединения fixtures\ms-sql-server-con-str.txt.
Если файл не найден - пишет что тест *не реализован*
